# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-07 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aroma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Hop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('usage', models.CharField(choices=[('AROM', 'Aroma'), ('BITT', 'Bittering'), ('BOTH', 'Aroma and Biterring')], max_length=4)),
                ('year', models.DateField()),
                ('oil_amount', models.PositiveIntegerField()),
                ('geraniol', models.PositiveIntegerField()),
                ('humulene', models.PositiveIntegerField()),
                ('farnesene', models.PositiveIntegerField()),
                ('caryophyllene', models.PositiveIntegerField()),
                ('linalool', models.PositiveIntegerField()),
                ('myrcene', models.PositiveIntegerField()),
                ('pinene', models.PositiveIntegerField()),
                ('alpha_acid', models.PositiveIntegerField()),
                ('beta_acid', models.PositiveIntegerField()),
                ('aroma', models.ManyToManyField(to='hop.Aroma')),
            ],
        ),
    ]
